// Primer-Anyo/Segundo cuatri/DAW/trabajos/Trabajo_3.25/ejemplos/vue/componente/DashboardView.vue
<template>
  <div id="app-container">
    <Header
      :user-role="userRole"
      :current-component="currentComponent"
      @change-component="changeComponent"
      @logout="handleLogout"
    />
    <main class="main-content">
      <component
        :is="currentComponentInstance"
        :user-role="userRole"
      ></component>
    </main>
  </div>
</template>

<script setup lang="ts">
import { ref, shallowRef, onMounted } from "vue";
import { useRouter } from "vue-router";
import Header from "@/components/Header.vue";
import ReservaPista from "@/components/ReservaPista.vue";
import Resenias from "@/components/Resenias.vue";
import Admin from "@/components/Admin.vue";
import AdminPistas from "@/components/AdminPistas.vue";
import AdminUsers from "@/components/AdminUsers.vue";

const router = useRouter();
const userRole = ref<"DEPORTISTA" | "ADMINISTRADOR">("DEPORTISTA");
const currentComponent = ref("ReservaPista");
const currentComponentInstance = shallowRef(ReservaPista);

const components = {
  ReservaPista,
  Resenias,
  Admin,
  AdminPistas,
  AdminUsers
};

const changeComponent = (componentName: string) => {
  currentComponent.value = componentName;
  currentComponentInstance.value =
    components[componentName as keyof typeof components];
};

onMounted(() => {
  const userStr = localStorage.getItem("user");
  if (userStr) {
    const user = JSON.parse(userStr);
    userRole.value = user.tipo;
  }
});

const handleLogout = () => {
  localStorage.removeItem("token");
  localStorage.removeItem("user");
  router.push("/login");
};
</script>

// Primer-Anyo/Segundo cuatri/DAW/trabajos/Trabajo_3.25/ejemplos/angular/componente/DashboardView.ts
import { Component, OnInit, Type } from '@angular/core';
import { Router } from '@angular/router';

import { ReservaPistaComponent } from './reserva-pista/reserva-pista.component';
import { ReseniasComponent }   from './resenias/resenias.component';
import { AdminComponent }      from './admin/admin.component';
import { AdminPistasComponent }from './admin-pistas/admin-pistas.component';
import { AdminUsersComponent } from './admin-users/admin-users.component';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']  
})
export class AppComponent implements OnInit {
  userRole: 'DEPORTISTA' | 'ADMINISTRADOR' = 'DEPORTISTA';
  currentComponentName = 'ReservaPista';
  currentComponentInstance!: Type<any>;

  // Mapa de nombres a clases de componente
  private componentsMap: Record<string, Type<any>> = {
    ReservaPista:   ReservaPistaComponent,
    Resenias:       ReseniasComponent,
    Admin:          AdminComponent,
    AdminPistas:    AdminPistasComponent,
    AdminUsers:     AdminUsersComponent
  };

  constructor(private router: Router) {}

  ngOnInit(): void {
    const userStr = localStorage.getItem('user');
    if (userStr) {
      const user = JSON.parse(userStr);
      this.userRole = user.tipo;
    }
    this.loadCurrentComponent();
  }

  private loadCurrentComponent() {
    this.currentComponentInstance =
      this.componentsMap[this.currentComponentName] ||
      ReservaPistaComponent;
  }

  changeComponent(componentName: string) {
    this.currentComponentName = componentName;
    this.loadCurrentComponent();
  }

  handleLogout() {
    localStorage.removeItem('token');
    localStorage.removeItem('user');
    this.router.navigate(['/login']);
  }
}
